name: PAINE Podcast
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: PAINE Podcast and Medical Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#e26625'
    - '#b2aeab'
    - '#ffffff'
    - '#329be3'
  brandStrength: 0
  lightness: 0.8981619833502918
  saturation: 0.855944289593026
  rhythmicContrast: 0.8744207909330726
purpose: []
