name: PAINE Podcast
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: PAINE Podcast and Medical Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#e26625'
    - '#b2aeab'
    - '#ffffff'
    - '#329be3'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
