name: PAINE Podcast
favicon: null
layout_spectrum: 0.77751
typography_spectrum: 1
title: PAINE Podcast and Medical Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#e26625'
    - '#b2aeab'
    - '#ffffff'
    - '#329be3'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
